/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PctGUI;

import ClasseGUI.Jogador;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Point;

/**
 *
 * @author Yure Pablo
 */
public class GUIJogo extends javax.swing.JFrame {
    Jogador guerreiro = new Jogador();
    java.awt.Dimension d = java.awt.Toolkit.getDefaultToolkit().getScreenSize(); 
    
            
    /**
     * Creates new form GUIJogo
     */
    public GUIJogo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPai = new javax.swing.JPanel();
        pnPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfVida = new javax.swing.JFormattedTextField();
        btSair = new javax.swing.JButton();
        btContinuar = new javax.swing.JButton();
        btComeçar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblRetângulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblGuerreiro = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn1 = new javax.swing.JPanel();
        lblTxt1 = new javax.swing.JLabel();
        lblTxt2 = new javax.swing.JLabel();
        lblConta = new javax.swing.JLabel();
        sp1 = new javax.swing.JScrollPane();
        txtExplicar = new javax.swing.JTextPane();
        sp2 = new javax.swing.JScrollPane();
        txtExplicar2 = new javax.swing.JTextPane();
        tftResposta = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pn5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(0,0,d.width,d.height);
        setPreferredSize(new java.awt.Dimension(1230, 730));

        PainelPai.setPreferredSize(new java.awt.Dimension(1200, 700));
        PainelPai.setLayout(new java.awt.CardLayout());

        pnPrincipal.setBackground(new java.awt.Color(255, 204, 204));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(1200, 700));
        pnPrincipal.setVerifyInputWhenFocusTarget(false);
        pnPrincipal.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Triângulo.png"))); // NOI18N
        pnPrincipal.add(jLabel2);
        jLabel2.setBounds(510, 20, 240, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Círculo3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnPrincipal.add(jLabel1);
        jLabel1.setBounds(540, 390, 200, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Losango.png"))); // NOI18N
        pnPrincipal.add(jLabel4);
        jLabel4.setBounds(300, 60, 230, 290);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Paralelogramo.png"))); // NOI18N
        pnPrincipal.add(jLabel5);
        jLabel5.setBounds(920, 90, 170, 100);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Vida:");
        pnPrincipal.add(jLabel8);
        jLabel8.setBounds(930, 0, 90, 60);

        tfVida.setEditable(false);
        tfVida.setForeground(new java.awt.Color(0, 255, 0));
        tfVida.setText("100");
        tfVida.setToolTipText("Integer");
        tfVida.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVidaActionPerformed(evt);
            }
        });
        pnPrincipal.add(tfVida);
        tfVida.setBounds(1030, 10, 120, 40);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        pnPrincipal.add(btSair);
        btSair.setBounds(960, 640, 90, 30);

        btContinuar.setText("Continuar");
        btContinuar.setEnabled(false);
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });
        pnPrincipal.add(btContinuar);
        btContinuar.setBounds(1080, 640, 100, 30);

        btComeçar.setText("Começar");
        btComeçar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComeçarActionPerformed(evt);
            }
        });
        pnPrincipal.add(btComeçar);
        btComeçar.setBounds(830, 640, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Quadrado.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        pnPrincipal.add(jLabel7);
        jLabel7.setBounds(120, 50, 160, 120);

        lblRetângulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Retângulo.png"))); // NOI18N
        pnPrincipal.add(lblRetângulo);
        lblRetângulo.setBounds(80, 230, 180, 390);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Trapézio Escaleno.png"))); // NOI18N
        pnPrincipal.add(jLabel9);
        jLabel9.setBounds(770, 210, 200, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Trapézio Retangulo.png"))); // NOI18N
        pnPrincipal.add(jLabel10);
        jLabel10.setBounds(880, 250, 130, 130);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Trapézio.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        pnPrincipal.add(jLabel11);
        jLabel11.setBounds(910, 400, 240, 150);

        lblGuerreiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Guerreiro.png"))); // NOI18N
        pnPrincipal.add(lblGuerreiro);
        lblGuerreiro.setBounds(10, 540, 80, 90);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Blue-wallpaper-simle-blue.jpg"))); // NOI18N
        pnPrincipal.add(jLabel14);
        jLabel14.setBounds(-20, -10, 1720, 900);

        PainelPai.add(pnPrincipal, "card0");

        pn1.setBackground(new java.awt.Color(255, 0, 0));
        pn1.setPreferredSize(new java.awt.Dimension(1200, 700));
        pn1.setLayout(null);

        lblTxt1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblTxt1.setText("O inimigo lhe atacou com uma vírgula!");
        pn1.add(lblTxt1);
        lblTxt1.setBounds(220, 26, 818, 56);

        lblTxt2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        lblTxt2.setText("Resolva esta divisão, aperte enter, e complete o desafio!");
        pn1.add(lblTxt2);
        lblTxt2.setBounds(122, 93, 992, 47);

        lblConta.setFont(new java.awt.Font("Times New Roman", 0, 150)); // NOI18N
        lblConta.setText("4,5 / 9,0");
        pn1.add(lblConta);
        lblConta.setBounds(358, 278, 494, 173);

        txtExplicar.setEditable(false);
        txtExplicar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtExplicar.setEnabled(false);
        sp1.setViewportView(txtExplicar);

        pn1.add(sp1);
        sp1.setBounds(30, 229, 250, 387);

        txtExplicar2.setEditable(false);
        txtExplicar2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtExplicar2.setEnabled(false);
        sp2.setViewportView(txtExplicar2);

        pn1.add(sp2);
        sp2.setBounds(920, 229, 250, 387);

        tftResposta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tftResposta.setText("Responda com ponto. Ex: 9.75");
        tftResposta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tftResposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tftRespostaMouseClicked(evt);
            }
        });
        tftResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftRespostaActionPerformed(evt);
            }
        });
        pn1.add(tftResposta);
        tftResposta.setBounds(384, 539, 448, 77);
        pn1.add(jLabel30);
        jLabel30.setBounds(564, 677, 0, 0);

        PainelPai.add(pn1, "card1");

        pn2.setBackground(new java.awt.Color(0, 0, 102));
        pn2.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("O inimigo lhe atacou com um +!");
        pn2.add(jLabel18);
        jLabel18.setBounds(280, 20, 700, 80);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Resolva essa soma, aperte enter, e complete este desafio!");
        pn2.add(jLabel19);
        jLabel19.setBounds(90, 100, 1050, 70);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 90)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("5,8765 + 3,9876");
        pn2.add(jLabel20);
        jLabel20.setBounds(310, 300, 690, 110);

        PainelPai.add(pn2, "card2");

        pn3.setBackground(new java.awt.Color(255, 255, 51));
        pn3.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel15.setText("O inimigo lhe atacou com um -!");
        pn3.add(jLabel15);
        jLabel15.setBounds(300, 40, 663, 56);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 42)); // NOI18N
        jLabel16.setText("Resolva essa subtração, aperte enter, e resolva este desafio!");
        pn3.add(jLabel16);
        jLabel16.setBounds(30, 130, 1139, 49);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 100)); // NOI18N
        jLabel17.setText("50,678 - 34,87");
        pn3.add(jLabel17);
        jLabel17.setBounds(320, 290, 583, 186);

        PainelPai.add(pn3, "card3");

        pn4.setBackground(new java.awt.Color(153, 153, 255));
        pn4.setPreferredSize(new java.awt.Dimension(1200, 700));
        pn4.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel21.setText("Você está numa encruzilhada, atacado com um X!");
        pn4.add(jLabel21);
        jLabel21.setBounds(80, 40, 1090, 56);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel22.setText("Resolva essa multiplicação, aperte enter, e complete este desafio!");
        pn4.add(jLabel22);
        jLabel22.setBounds(30, 160, 1237, 49);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 150)); // NOI18N
        jLabel23.setText("8,9*10,5");
        pn4.add(jLabel23);
        jLabel23.setBounds(350, 310, 526, 173);

        PainelPai.add(pn4, "card4");

        pn5.setBackground(new java.awt.Color(0, 255, 255));
        pn5.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel24.setText("O inimigo lhe atacou com uma vírgula!");
        pn5.add(jLabel24);
        jLabel24.setBounds(201, 40, 818, 56);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 42)); // NOI18N
        jLabel25.setText("Resolva esta divisão, aperte enter, e complete este desafio!");
        pn5.add(jLabel25);
        jLabel25.setBounds(50, 130, 1116, 49);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 120)); // NOI18N
        jLabel26.setText("5,67 / 2,897");
        pn5.add(jLabel26);
        jLabel26.setBounds(310, 270, 740, 226);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 30)); // NOI18N
        jLabel6.setText("Utilize 3 casas decimais");
        pn5.add(jLabel6);
        jLabel6.setBounds(30, 170, 430, 90);

        PainelPai.add(pn5, "card5");

        pn6.setBackground(new java.awt.Color(51, 51, 0));
        pn6.setPreferredSize(new java.awt.Dimension(1600, 904));
        pn6.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("O inimigo lhe atacou com um +-!");
        pn6.add(jLabel27);
        jLabel27.setBounds(262, 37, 691, 56);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 42)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Resolva este problema, aperte enter e complete este desafio!");
        pn6.add(jLabel28);
        jLabel28.setBounds(23, 129, 1147, 49);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 65)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("(9+4)-(8-9)*(1/7)/(8*6)");
        pn6.add(jLabel29);
        jLabel29.setBounds(290, 330, 660, 76);

        jLabel3.setFont(new java.awt.Font("Arial", 2, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Utilize 3 casas decimais");
        pn6.add(jLabel3);
        jLabel3.setBounds(30, 170, 430, 90);

        PainelPai.add(pn6, "card6");

        pn7.setBackground(new java.awt.Color(51, 51, 51));
        pn7.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Uma forma do inimigo está prestes a ser destruída!");
        pn7.add(jLabel33);
        jLabel33.setBounds(51, 35, 1091, 56);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 42)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Resolva a área da forma geométrica e complete este desafio!");
        pn7.add(jLabel34);
        jLabel34.setBounds(23, 109, 1150, 49);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 60)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Você percorreu 1260m  ");
        pn7.add(jLabel35);
        jLabel35.setBounds(330, 270, 585, 70);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("O comprimento é 1,625 vezes maior que a largura");
        pn7.add(jLabel36);
        jLabel36.setBounds(310, 370, 600, 36);

        PainelPai.add(pn7, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPai, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPai, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btComeçarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComeçarActionPerformed
        // TODO add your handling code here:
        pnPrincipal.setVisible(false);
        pn1.setVisible(true);
        btContinuar.setEnabled(true);

    }//GEN-LAST:event_btComeçarActionPerformed

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) PainelPai.getLayout();
        String nome = "card"+guerreiro.getQuant();
        card.show(PainelPai, nome);
    }//GEN-LAST:event_btContinuarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void tfVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVidaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfVidaActionPerformed

    private void tftRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftRespostaActionPerformed
        // TODO add your handling code here:
        if (tftResposta.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Como você vai continuar sem ao menos tentar?! Informe os dados!");
        }
        else{
            int altura = txtExplicar.getHeight();
            int largura = txtExplicar.getWidth();
            guerreiro.Responder();
            float r = Float.parseFloat(tftResposta.getText());
            if (r == guerreiro.getResposta()){
                JOptionPane.showMessageDialog(this, "Parabéns! Você acertou!");
                CardLayout c = (CardLayout) PainelPai.getLayout();
                c.first(PainelPai);

                guerreiro.location();
                lblGuerreiro.setLocation(guerreiro.getX(), guerreiro.getY());

                btComeçar.setEnabled(false);
                tfVida.setText(String.valueOf(guerreiro.getVida()));
                guerreiro.contar();
                tftResposta.setText("Responda com ponto. Ex: 9.75");
                txtExplicar.setText(null);
                txtExplicar2.setText(null);
                txtExplicar.setEnabled(false);
                txtExplicar2.setEnabled(false);
                if (guerreiro.getQuant()==2){
                    pn2.add(tftResposta);
                    pn2.add(sp1);//resolver
                    pn2.add(sp2);
                }
                if (guerreiro.getQuant()==3){
                    pn3.add(tftResposta);
                    pn3.add(sp1);//resolver
                    pn3.add(sp2);
                }
                if (guerreiro.getQuant()==4){
                    pn4.add(tftResposta);
                    pn4.add(sp1);//resolver
                    pn4.add(sp2);
                }
                if (guerreiro.getQuant()==5){
                    pn5.add(tftResposta);
                    pn5.add(sp1);//resolver
                    pn5.add(sp2);
                }
                if (guerreiro.getQuant()==6){
                    pn6.add(tftResposta);
                    pn6.add(sp1);//resolver
                    pn6.add(sp2);
                }
                if (guerreiro.getQuant()==7){
                    pn7.add(tftResposta);
                    pn7.add(sp1);//resolver
                    pn7.add(sp2);
                }
                if (guerreiro.getQuant()==8){
                    JOptionPane.showMessageDialog(this,"Parabéns! Etapa Completa!");
                    lblRetângulo.setVisible(false);
                    lblGuerreiro.setLocation(60,140);
                }

                txtExplicar.setLocation(20, 350);
                txtExplicar2.setLocation(1320, 350);
                txtExplicar.setSize(largura, altura);
                txtExplicar2.setSize(largura, altura);

            }
            else{
                if (guerreiro.getVida()>0){
                    guerreiro.setVida(10);
                    JOptionPane.showMessageDialog(this,"Resposta Errada! Você tem "+guerreiro.getVida()+" de vida!");
                    txtExplicar.setEnabled(true);
                    txtExplicar2.setEnabled(true);
                    txtExplicar.setText(guerreiro.Imprimir1());
                    txtExplicar2.setText(guerreiro.Imprimir2());
                    tftResposta.setText(null);
                    tftResposta.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Você perdeu! A resposta era "+guerreiro.getResposta());
                    System.exit(0);
                }
            }
        }
    }//GEN-LAST:event_tftRespostaActionPerformed

    private void tftRespostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tftRespostaMouseClicked
        // TODO add your handling code here:
        tftResposta.setText(null);
    }//GEN-LAST:event_tftRespostaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPai;
    private javax.swing.JButton btComeçar;
    private javax.swing.JButton btContinuar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblGuerreiro;
    private javax.swing.JLabel lblRetângulo;
    private javax.swing.JLabel lblTxt1;
    private javax.swing.JLabel lblTxt2;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JPanel pn5;
    private javax.swing.JPanel pn6;
    private javax.swing.JPanel pn7;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JFormattedTextField tfVida;
    private javax.swing.JFormattedTextField tftResposta;
    private javax.swing.JTextPane txtExplicar;
    private javax.swing.JTextPane txtExplicar2;
    // End of variables declaration//GEN-END:variables
}
